### ISSUE TITLE
Использование дополнительных библиотек во втором задании

### ISSUE THREAD

**Issue by StanleySB** [martyns0n/kode-internship-test-task-2020#2]
Добрый день. Хотел уточнить, можно ли в проекте использовать доп. библиотеки для второго задания? 
К примеру, axios и bootstrap
Так же вопрос на счет препроцессоров, возможно ли их использование? 
Заранее извиняюсь, если это где-то было, но я проглядел

**Comment by Eyvgeniy** [comment]
Добрый день!
Присоединяюсь к вопросу.

**Comment by m0rtyn** [comment]
👀
Извините, что обманул со скоростью ответа. Упустил ишью потому что не был подписан. 
Лечу на помощь.

**Comment by m0rtyn** [comment]
@StanleySB @Eyvgeniy
Всё хорошо с дополнительными либами во втором задании. Использовать можно.
