### ISSUE TITLE
Подтверждение логина реализованное с помощью One Time Password (OTP).

### ISSUE THREAD

**Issue by Eyvgeniy** [martyns0n/kode-internship-test-task-2020#4]
Добрый день!
Какой должен быть механизм  доставки одноразового пароля?

**Comment by m0rtyn** [comment]
Привет, без заморочек.

Мы ожидаем лишь заглушки, которая работает как OTP. Важнее сделать валидацию ввода пароля.

UPD: запросы слать и запрашивать извне при реализации OTP не нужно. Лучше изолировать «доставку» в метод, который будто бы получает это пароль для проверки.

Чтобы мы могли войти и проверить задание **стоит отобразить правильный пароль в консоли или алёртом.**
